services:
  - type: web
    name: searxng
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free # Change to a paid plan if you need more resources
    healthCheckPath: /
    envVars:
      - key: SEARXNG_SECRET
        generateValue: true
      - key: SEARXNG_PORT
        value: 8080
      - key: SEARXNG_BASE_URL
        fromContext: instance_url
      - key: SEARXNG_VALKEY_URL
        value: valkey://valkey:6379/0
      - key: SEARXNG_LIMITER
        value: "true"

  - type: private
    name: valkey
    env: image
    image: valkey/valkey:latest
    plan: free
    envVars:
      - key: VALKEY_PORT
        value: 6379
