services:
  - type: web
    name: searxng
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free # Change to a paid plan if you need more resources
    healthCheckPath: /
    envVars:
      - key: SEARXNG_SECRET
        generateValue: true
      - key: SEARXNG_PORT
        value: 8080
      - key: SEARXNG_BASE_URL
        value: "https://your-app-url.onrender.com"
      - key: SEARXNG_VALKEY_URL
        fromService:
          type: keyvalue
          name: cache
          property: connectionString
      - key: SEARXNG_LIMITER
        value: "true"

  - type: keyvalue
    name: cache
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: internal
